private_worker: ${private_worker02}
properties:
  - type: secure
    name: apikey
    value: ""
  - type: text
    name: repository
    value: https://github.com/kristinochka/zopeneditor-sample
  - type: secure
    name: zos-ssh-key
    value: ""
  - type: text
    name: zos-ssh-port
    value: ""
  - type: text
    name: zos-host
    value: ""
triggers:
  - type: manual
    name: Manual Trigger - 0
    eventListener: listener
    properties: []
    private_worker: wazidev-worker-kristina
    concurrency:
      limited: true
      maxConcurrentRuns: 1
inputs:
  - type: git
    path: .tekton
    branch: master
    service: ${githubconsolidated00}
