properties:
  - type: secure
    name: apikey
    value: ""
  - type: text
    name: repository
    value: https://github.com/kristinochka/tekton-wazi-pipeline
  - type: secure
    name: zos-ssh-key
    value: ""
  - type: text
    name: zos-ssh-port
    value: ""
  - type: text
    name: zos-host
    value: ""
triggers:
  - type: manual
    name: Manual Trigger - 0
    eventListener: listener
    properties: []
    concurrency:
      limited: true
      maxConcurrentRuns: 1
  - type: git
    branch: use-provided-worker
    events:
      push: true
      pull_request: true
    name: Git Trigger - 0
    eventListener: listener
    properties: []
    service: ${githubconsolidated00}
inputs:
  - type: git
    path: .tekton
    branch: use-provided-worker
    service: ${githubconsolidated00}
