apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: dbb-build-task
spec:
  params:
    - name: repository
      description: the git repo
    - name: branch
      description: the branch for the git repo
      default: master
    - name: apikey
      description: the ibmcloud api key
    - name: zos-ssh-key
      description: The z/OS SSH private key
    - name: zos-host
      description: The z/OS host name
    - name: zos-ssh-port
      description: The z/OS SSH port
    - name: app-name
      description: The application name
    - name: git-repository
      description: The url of the git repository
    - name: git-branch
      description: The repository branch on which the build has been performed
    - name: git-commit
      description: The git commit id
  workspaces:
    - name: output
      mountPath: /artifacts
  steps:
    - name: dbb-build
      image: ibmcom/pipeline-base-image:2.13
      env:
        - name: REPOSITORY
          value: $(params.repository)
        - name: BRANCH
          value: $(params.branch)
        - name: IBMCLOUD_API_KEY
          value: $(params.apikey)
        - name: ZOS_SSH_KEY
          value: $(params.zos-ssh-key)
        - name: ZOS_HOST
          value: $(params.zos-host)
        - name: ZOS_SSH_PORT
          value: $(params.zos-ssh-port)
        - name: APP_NAME
          value: $(params.app-name)
        - name: GIT_URL
          value: $(params.git-repository)
        - name: GIT_BRANCH
          value: $(params.git-branch)
        - name: GIT_COMMIT
          value: $(params.git-commit)
        - name: JOB_URL
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['devops.cloud.ibm.com/pipeline-run-url']
        - name: BUILD_NUMBER
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['devops.cloud.ibm.com/build-number']
      securityContext:
        privileged: true
      script: |
        #!/bin/bash
        set -x
        echo $PWD
        whoami
        echo $ZOS_SSH_KEY | base64 -w 0 --decode > id_rsa
        chmod 700 id_rsa
        WORKSPACE_DIR="$(workspaces.output.path)"
        ZOS_WORK_DIR=/u/ibmuser/tekton
        cd /artifacts; cd git; ls -la
        sftp -o "StrictHostKeyChecking=no" -i id_rsa -P $ZOS_SSH_PORT ibmuser@$ZOS_HOST << EOF
        get $WORKSPACE_DIR/git/.tekton/dbb-build.sh $ZOS_WORK_DIR
        EOF
        ssh -i id_rsa -o "StrictHostKeyChecking=no" ibmuser@$ZOS_HOST -p $ZOS_SSH_PORT "$ZOS_WORK_DIR/dbb-build.sh"
        rc=$?
      volumeMounts:
        - mountPath: /cd-config
          name: cd-config-volume
  volumes:
    - name: cd-config-volume
      configMap:
        name: toolchain
        items:
          - key: toolchain.json
            path: toolchain.json
